clusterName: flink-custer
flinkVersion: v1_19
restartNonce: 1
flinkConfiguration: {}
mode: native
image:
  repository: flink
  tag: 1.19.1-scala_2.12-java17
  pullPolicy: IfNotPresent
serviceAccount:
  create: true
  name: flink-cluster
  rbac:
    enabled: true
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
          - pods
        verbs:
          - "*"
      - apiGroups:
          - apps
        resources:
          - deployments
        verbs:
          - "*"
jobManager:
  resource:
    memory: "1024m"
    cpu: 1
taskManager:
  resource:
    cpu: 1
    memory: "1024m"
ingress:
  template: "flink.k8s.io/{{namespace}}/{{name}}(/|$)(.*)"
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  labels: {}
  tls: []

