apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
  flinkVersion: {{ .Values.flinkVersion }}
  restartNonce: {{ .Values.restartNonce | default 1 }}
  mode: {{ .Values.mode | default "standalone" }}
  {{- with .Values.flinkConfiguration}}
  flinkConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccount: {{ .Values.serviceAccount.name }}
  {{- with .Values.jobManager }}
  jobManager:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.taskManager }}
  taskManager:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}