{{- if .Values.default.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.default.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.default.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}

---
{{- if .Values.default.serviceAccount.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.default.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.default.serviceAccount.rbac.rules }}
rules:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}

---
{{- if .Values.default.serviceAccount.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.default.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.default.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.default.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}